In [3]:

import torch
import numpy as np


In [4]:
# Initialize empty tensor
print("\n1. Empty tensor (uninitialized):")
x = torch.empty(3, 4)
print(f"   torch.empty(3, 4):\n{x}")



1. Empty tensor (uninitialized):
   torch.empty(3, 4):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [6]:

# Initialize with random values
print("\n2. Random initialization:")
x = torch.rand(3, 4)
print(f"   torch.rand(3, 4):\n{x}")


2. Random initialization:
   torch.rand(3, 4):
tensor([[0.5147, 0.7327, 0.9716, 0.3073],
        [0.4678, 0.4495, 0.4560, 0.3563],
        [0.8985, 0.5103, 0.8829, 0.9918]])


In [7]:
# Initialize from data
print("\n4. From data:")
data = [[1, 2], [3, 4], [5, 6]]
x = torch.tensor(data)
print(f"   torch.tensor({data}):\n{x}")
print(f"   dtype: {x.dtype}")


4. From data:
   torch.tensor([[1, 2], [3, 4], [5, 6]]):
tensor([[1, 2],
        [3, 4],
        [5, 6]])
   dtype: torch.int64


In [8]:
x = torch.rand(3, 4, 5)
print(f"\nTensor: torch.rand(3, 4, 5)")
print(f"   Shape: {x.shape}")
print(f"   Dtype: {x.dtype}")
print(f"   Device: {x.device}")



Tensor: torch.rand(3, 4, 5)
   Shape: torch.Size([3, 4, 5])
   Dtype: torch.float32
   Device: cpu


In [9]:
# Addition
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

print(f"\n5. Addition:")
print(f"   x =\n{x}")
print(f"   y =\n{y}")
print(f"   x + y =\n{x + y}")
print(f"   torch.add(x, y) =\n{torch.add(x, y)}")



5. Addition:
   x =
tensor([[1, 2],
        [3, 4]])
   y =
tensor([[5, 6],
        [7, 8]])
   x + y =
tensor([[ 6,  8],
        [10, 12]])
   torch.add(x, y) =
tensor([[ 6,  8],
        [10, 12]])


In [10]:
# In-place addition
print(f"\n   In-place: y.add_(x) modifies y")
y_copy = y.clone()
y_copy.add_(x)
print(f"   After add_: {y_copy}")



   In-place: y.add_(x) modifies y
   After add_: tensor([[ 6,  8],
        [10, 12]])


In [11]:
# Matrix multiplication
print(f"\n6. Matrix multiplication:")
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
b = torch.tensor([[7, 8], [9, 10], [11, 12]])
print(f"   a @ b =\n{a @ b}")
print(f"   torch.matmul(a, b) =\n{torch.matmul(a, b)}")



6. Matrix multiplication:
   a @ b =
tensor([[ 58,  64],
        [139, 154]])
   torch.matmul(a, b) =
tensor([[ 58,  64],
        [139, 154]])


In [12]:
# Element-wise multiplication
print(f"\n7. Element-wise multiplication:")
print(f"   x * y =\n{x * y}")



7. Element-wise multiplication:
   x * y =
tensor([[ 5, 12],
        [21, 32]])


In [13]:
# Broadcasting
print(f"\n8. Broadcasting:")
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.tensor([10, 20, 30])
print(f"   x =\n{x}")
print(f"   y = {y}")
print(f"   x + y =\n{x + y}")


8. Broadcasting:
   x =
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
   y = tensor([10, 20, 30])
   x + y =
tensor([[11, 22, 33],
        [14, 25, 36],
        [17, 28, 39]])


In [17]:
x = torch.randn(4, 4)
print(f"\nOriginal shape: {x.shape}")
print(f"x = {x}")

y = x.view(16)
print(f"view(16): {y.shape}")
print(f"y = {y}")

y = x.view(-1, 8)  # -1 lets PyTorch infer the size
print(f"view(-1, 8): {y.shape}")
print(f"y = {y}")


Original shape: torch.Size([4, 4])
x = tensor([[-0.8426,  0.0868, -0.5386, -0.0759],
        [-0.5921, -1.2162, -0.0460,  0.8088],
        [-0.4908, -0.1401, -0.4435, -0.7492],
        [ 1.4598,  0.0392,  1.6659,  0.6089]])
view(16): torch.Size([16])
y = tensor([-0.8426,  0.0868, -0.5386, -0.0759, -0.5921, -1.2162, -0.0460,  0.8088,
        -0.4908, -0.1401, -0.4435, -0.7492,  1.4598,  0.0392,  1.6659,  0.6089])
view(-1, 8): torch.Size([2, 8])
y = tensor([[-0.8426,  0.0868, -0.5386, -0.0759, -0.5921, -1.2162, -0.0460,  0.8088],
        [-0.4908, -0.1401, -0.4435, -0.7492,  1.4598,  0.0392,  1.6659,  0.6089]])


In [18]:
# Torch to NumPy
print("\n9. Torch to NumPy:")
a = torch.ones(5)
print(f"   Torch tensor: {a}")
b = a.numpy()
print(f"   NumPy array: {b}")



9. Torch to NumPy:
   Torch tensor: tensor([1., 1., 1., 1., 1.])
   NumPy array: [1. 1. 1. 1. 1.]


In [19]:
# Note: They share memory
a.add_(1)
print(f"   After add_(1) to tensor:")
print(f"   Torch tensor: {a}")
print(f"   NumPy array: {b}")


   After add_(1) to tensor:
   Torch tensor: tensor([2., 2., 2., 2., 2.])
   NumPy array: [2. 2. 2. 2. 2.]


In [20]:

if torch.cuda.is_available():
    print(f"\nCUDA is available!")
    print(f"CUDA device: {torch.cuda.get_device_name(0)}")
    
    # Create tensor on GPU
    x = torch.ones(3, 3, device='cuda')
    print(f"\nTensor on GPU:\n{x}")
    print(f"Device: {x.device}")
    
    # Move tensor to GPU
    y = torch.ones(3, 3)
    y = y.to('cuda')
    print(f"\nMoved to GPU:\n{y}")
    
    # Operations on GPU
    z = x + y
    print(f"\nGPU operation result:\n{z}")
    
    # Move back to CPU
    z_cpu = z.to('cpu')
    print(f"\nBack on CPU: {z_cpu.device}")
else:
    print("\nCUDA not available. Install PyTorch with CUDA for GPU support.")
    
    section("SUMMARY")
    print("""
    Key takeaways:
    1. Tensors are the fundamental data structure in PyTorch
    2. Similar to NumPy arrays but with GPU support and autograd
    3. Operations have both functional (torch.add) and method (tensor.add) forms
    4. In-place operations end with underscore (add_)
    5. Tensors can share memory with NumPy arrays
    6. Easy to move between CPU and GPU with .to() method
    """)



CUDA not available. Install PyTorch with CUDA for GPU support.

  SUMMARY

    Key takeaways:
    1. Tensors are the fundamental data structure in PyTorch
    2. Similar to NumPy arrays but with GPU support and autograd
    3. Operations have both functional (torch.add) and method (tensor.add) forms
    4. In-place operations end with underscore (add_)
    5. Tensors can share memory with NumPy arrays
    6. Easy to move between CPU and GPU with .to() method
    


In [21]:
print(torch.backends.mps.is_available())  # 应该输出 True
print(torch.backends.mps.is_built())      # 应该输出 True

True
True


In [27]:
# Create a tensor with requires_grad=True
print("\n1. Creating tensors with gradient tracking:")
x = torch.ones(2, 2, requires_grad=True)
print(f"   x = torch.ones(2, 2, requires_grad=True)")
print(f"   x =\n{x}")
print(f"   x.requires_grad = {x.requires_grad}")


# Perform operations
print("\n2. Performing operations:")
y = x + 2
print(f"   y = x + 2 =\n{y}")
print(f"   y.requires_grad = {y.requires_grad}")
print(f"   y.grad_fn = {y.grad_fn}")

z = y * y * 3
out = z.mean()

print(f"\n   z = y * y * 3 =\n{z}")
print(f"   z.grad_fn = {z.grad_fn}")
print(f"\n   out = z.mean() = {out}")
print(f"   out.grad_fn = {out.grad_fn}")

print("\n3. Computing gradients:")
print(f"   Before backward: x.grad = {x.grad}")

# Compute gradients
out.backward()

print(f"   After backward: x.grad =\n{x.grad}")

# Mathematical explanation
print("\n   Math check:")
print("   out = 1/4 * sum(z)")
print("   z = 3 * y^2 = 3 * (x+2)^2")
print("   d(out)/dx = 1/4 * 6 * (x+2) = 3/2 * (x+2)")
print(f"   With x=1: d(out)/dx = 3/2 * 3 = 4.5")



1. Creating tensors with gradient tracking:
   x = torch.ones(2, 2, requires_grad=True)
   x =
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
   x.requires_grad = True

2. Performing operations:
   y = x + 2 =
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
   y.requires_grad = True
   y.grad_fn = <AddBackward0 object at 0x113e0dc30>

   z = y * y * 3 =
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
   z.grad_fn = <MulBackward0 object at 0x113e0dc30>

   out = z.mean() = 27.0
   out.grad_fn = <MeanBackward0 object at 0x113e0dc30>

3. Computing gradients:
   Before backward: x.grad = None
   After backward: x.grad =
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

   Math check:
   out = 1/4 * sum(z)
   z = 3 * y^2 = 3 * (x+2)^2
   d(out)/dx = 1/4 * 6 * (x+2) = 3/2 * (x+2)
   With x=1: d(out)/dx = 3/2 * 3 = 4.5


In [29]:

print("\n4. Non-scalar output backward:")
x = torch.randn(3, requires_grad=True)
print(f"   x = {x}")

y = x * 2
print(f"\n   y = x * 2 = {y}")

# For non-scalar output, we need to pass a gradient vector
v = torch.tensor([1.0, 2.0, 3.0])
y.backward(v)

print(f"\n   y.backward({v})")
print(f"   x.grad = {x.grad}")
print("   (This is the vector-Jacobian product)")


4. Non-scalar output backward:
   x = tensor([-1.2380,  0.7985,  1.4156], requires_grad=True)

   y = x * 2 = tensor([-2.4760,  1.5970,  2.8312], grad_fn=<MulBackward0>)

   y.backward(tensor([1., 2., 3.]))
   x.grad = tensor([2., 4., 6.])
   (This is the vector-Jacobian product)


In [31]:
print("\n5. Ways to stop gradient tracking:")

x = torch.ones(2, 2, requires_grad=True)
print(f"   x.requires_grad = {x.requires_grad}")

# Method 1: torch.no_grad()
print("\n   Method 1: with torch.no_grad():")
with torch.no_grad():
    y = x + 2
    print(f"      y.requires_grad = {y.requires_grad}")

# Method 2: detach()
print("\n   Method 2: .detach():")
z = x.detach()
print(f"      z.requires_grad = {z.requires_grad}")
print(f"      z shares memory with x: {z.data_ptr() == x.data_ptr()}")

# Method 3: Set requires_grad=False
# print("\n   Method 3: Set requires_grad=False:")
# w = x.clone()
# w.requires_grad = False
# print(f"      w.requires_grad = {w.requires_grad}")



5. Ways to stop gradient tracking:
   x.requires_grad = True

   Method 1: with torch.no_grad():
      y.requires_grad = False

   Method 2: .detach():
      z.requires_grad = False
      z shares memory with x: True


In [28]:
import torch

class MyCube(torch.autograd.Function):
    
    @staticmethod
    def forward(ctx, x):
        """
        正向传播
        """
        # 1. 留下线索：把 x 存进上下文 (ctx) 中，因为后面求导 dy/dx = 3x^2 需要用到 x 的值
        ctx.save_for_backward(x)
        
        # 2. 【核心答案】：forward 返回的是真实的数学计算结果
        result = x ** 3
        return result

    @staticmethod
    def backward(ctx, grad_output):
        """
        反向传播
        """
        # 1. 顺藤摸瓜：从上下文 (ctx) 中取出刚才存下的 x
        x, = ctx.saved_tensors
        
        # 2. 计算局部的导数：根据微积分，y = x^3 的导数是 3x^2
        local_grad = 3 * (x ** 2)
        
        # 3. 【核心答案】：backward 返回的是 链式法则的结果 = 上游传来的梯度 * 局部梯度
        # 注意：forward 接收了几个参数（除了 ctx），这里就必须返回几个梯度！
        # 如果某个参数不需要梯度，返回 None。
        return grad_output * local_grad

# --- 测试运行 ---
x = torch.tensor([2.0], requires_grad=True)

# 1. 执行 forward：拿到结果
y = MyCube.apply(x) 
print("forward 返回的结果:", y)  # 输出: tensor([8.], grad_fn=<MyCubeBackward>)

# 假设最终的 Loss 就是 y 自己，我们对 y 调用 backward
# 这时底层会向上游传递一个默认的梯度 1.0 作为 grad_output
y.backward()

# 2. 执行 backward 后：拿到梯度
print("backward 算出的梯度:", x.grad) # 输出: tensor([12.]) (因为 1.0 * 3 * 2^2 = 12)

forward 返回的结果: tensor([8.], grad_fn=<MyCubeBackward>)
backward 算出的梯度: tensor([12.])


In [33]:
print("\n6. In-place operations and autograd:")
x = torch.ones(2, 2, requires_grad=True)
print(f"   x = {x}")

try:
    y = x + 2
    x.add_(1)  # In-place operation
    y.backward(torch.ones_like(y))
except RuntimeError as e:
    print(f"   Error: {e}")

print("\n   In-place ops can cause issues with autograd if they modify")
print("   tensors needed for backward pass.")

section("COMPUTATIONAL GRAPH VISUALIZATION")

print("\n7. Building a computational graph:")

# Reset
x = torch.tensor(2.0, requires_grad=True)
w = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

# Forward pass
u = w * x
v = u + b
a = torch.relu(v)

print(f"   x = {x.item()}")
print(f"   w = {w.item()}")
print(f"   b = {b.item()}")
print(f"\n   u = w * x = {u.item()}")
print(f"   v = u + b = {v.item()}")
print(f"   a = relu(v) = {a.item()}")

print("\n   Computational graph:")
print("   x, w, b -> [mul] -> u -> [add] -> v -> [relu] -> a")

# Backward
a.backward()

print("\n   Gradients:")
print(f"   da/dx = {x.grad.item()}")
print(f"   da/dw = {w.grad.item()}")
print(f"   da/db = {b.grad.item()}")



6. In-place operations and autograd:
   x = tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
   Error: a leaf Variable that requires grad is being used in an in-place operation.

   In-place ops can cause issues with autograd if they modify
   tensors needed for backward pass.

  COMPUTATIONAL GRAPH VISUALIZATION

7. Building a computational graph:
   x = 2.0
   w = 3.0
   b = 1.0

   u = w * x = 6.0
   v = u + b = 7.0
   a = relu(v) = 7.0

   Computational graph:
   x, w, b -> [mul] -> u -> [add] -> v -> [relu] -> a

   Gradients:
   da/dx = 3.0
   da/dw = 2.0
   da/db = 1.0
