# NumPy and pandas Basics

This notebook is a hands-on starting point for learning array programming with NumPy and table analysis with pandas.

## 1. Imports

In [2]:
from pathlib import Path

import numpy as np
import pandas as pd

DATA_DIR = Path("../data")
np.__version__, pd.__version__

('2.5.0', '3.0.3')

## 2. NumPy: arrays, shape, dtype

In [3]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
print("shape:", a.shape)
print("dtype:", a.dtype)
print("first row:", a[0])
print("second column:", a[:, 1])

shape: (3, 4)
dtype: int64
first row: [0 1 2 3]
second column: [1 5 9]


## 3. NumPy: vectorization and broadcasting

In [5]:
prices = np.array([9.9, 1.5, 39.0])
units = np.array([12, 40, 5])
revenue = prices * units
revenue

array([118.8,  60. , 195. ])

In [6]:
matrix = np.arange(1, 13).reshape(3, 4)
mat
column_discount = np.array([[1.0], [0.9], [0.8]])
matrix * column_discount

array([[1. , 2. , 3. , 4. ],
       [4.5, 5.4, 6.3, 7.2],
       [7.2, 8. , 8.8, 9.6]])

Exercise: create a 5x5 random matrix, then compute row sums and column means.

In [ ]:
rng = np.random.default_rng(seed=42)
m = rng.normal(loc=0, scale=1, size=(5, 5))
row_sums = m.sum(axis=1)
column_means = m.mean(axis=0)
m, row_sums, column_means

## 4. pandas: load and inspect data

In [12]:
sales = pd.read_csv(DATA_DIR / "sales.csv", parse_dates=["date"])
sales.head()

,date,region,product,channel,units,unit_price,discount
0,2026-01-03,North,Notebook,Online,12,9.9,0.05
1,2026-01-04,East,Pen,Store,40,1.5,0.00
2,2026-01-05,South,Backpack,Online,5,39.0,0.10
3,2026-01-06,West,Notebook,Store,18,9.9,0.00
4,2026-01-07,North,Pen,Online,55,1.5,0.05


In [ ]:
sales.info()
sales.describe(include="all")

## 5. pandas: select, filter, assign

In [ ]:
sales = sales.assign(
    gross_revenue=sales["units"] * sales["unit_price"],
    net_revenue=lambda df: df["gross_revenue"] * (1 - df["discount"]),
)
sales.loc[sales["channel"].eq("Online"), ["date", "region", "product", "net_revenue"]]

## 6. pandas: groupby and pivot tables

In [ ]:
region_summary = (
    sales.groupby("region", as_index=False)
    .agg(
        orders=("date", "count"),
        units=("units", "sum"),
        revenue=("net_revenue", "sum"),
    )
    .sort_values("revenue", ascending=False)
)
region_summary

In [ ]:
pd.pivot_table(
    sales,
    index="region",
    columns="product",
    values="net_revenue",
    aggfunc="sum",
    fill_value=0,
    margins=True,
)

## 7. Export results

In [ ]:
region_summary.to_csv(DATA_DIR / "region_summary.csv", index=False)
region_summary.to_parquet(DATA_DIR / "region_summary.parquet", index=False)
region_summary

Next practice ideas:

- Add a `month` column from `date` and aggregate by month.
- Find the product with the highest average discount.
- Plot revenue by region using `region_summary.plot.bar(...)`.